### ISSUE TITLE
Error: "Client does not support challenges that will satisfy the CA"

### ISSUE THREAD

**Issue by JoeTN** [ebarault/letsencrypt-autorenewal#1]
Hello

I'm using the following docker-compose: https://pastebin.com/veJ20PA9 

When doing so I get the following error in the log:
`AuthorizationError: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.`

Do you know a solution to this ?
I'm running the container in Qnap's ContainerStation.

Regards
Joe

**Comment by JoeTN** [comment]
So it seems that the image uses the challenge type tls-sni which is disabled for security reasons: https://community.letsencrypt.org/t/tls-sni-challenges-disabled-for-most-new-issuance/50316

Are you planning on implementing other challenge types ?

**Comment by ebarault** [comment]
hi @JoeTN, sorry to here that this release does not match your requirements
I do not have a lot of time to look around this, would you like to propose a pull request?

**Comment by ebarault** [comment]
@JoeTN this is solved now
