### ISSUE TITLE
Handling of multi-host domains

### ISSUE THREAD

**Issue by 2sheds** [ebarault/letsencrypt-autorenewal#2]
If multi-host domains are provided, as instructed, comma-separated (e.g. `www1.example.com,www2.example.com`) the resulting files will be placed by certbot under  the first domain's name, i.e. `/etc/letsencrypt/live/www1.example.com/*` but on the next run the script (both `copyCertificates()` and `processCertificates()` procedures) will search for the full string and thus never finds them, always re-issuing them anew.

**Comment by ebarault** [comment]
hi @2sheds , thanks for opening this issue, i'm testing your fix right now

**Comment by ebarault** [comment]
docker image 1.1.3 is available on dockerhub 🎉 
https://hub.docker.com/r/ebarault/letsencrypt-autorenew-docker/tags
